# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 465)
        MainWindow.setStyleSheet("#MainWindow\n"
"{\n"
"background-color: qconicalgradient(cx:1, cy:0.966, angle:0, stop:0 rgba(10, 90, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 10, 601, 391))
        self.tabWidget.setStyleSheet("#tabWidget\n"
"{\n"
"background-color: qconicalgradient(cx:1, cy:0.966, angle:0, stop:0 rgba(10, 90, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidgetJ1 = QtWidgets.QTableWidget(self.tab)
        self.tableWidgetJ1.setGeometry(QtCore.QRect(0, 10, 601, 361))
        self.tableWidgetJ1.setObjectName("tableWidgetJ1")
        self.tableWidgetJ1.setColumnCount(9)
        self.tableWidgetJ1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ1.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ1.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidgetJ2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidgetJ2.setGeometry(QtCore.QRect(0, 10, 601, 361))
        self.tableWidgetJ2.setObjectName("tableWidgetJ2")
        self.tableWidgetJ2.setColumnCount(9)
        self.tableWidgetJ2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ2.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidgetJ3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidgetJ3.setGeometry(QtCore.QRect(0, 10, 601, 361))
        self.tableWidgetJ3.setObjectName("tableWidgetJ3")
        self.tableWidgetJ3.setColumnCount(9)
        self.tableWidgetJ3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetJ3.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidgetTotal = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidgetTotal.setGeometry(QtCore.QRect(0, 10, 601, 361))
        self.tableWidgetTotal.setObjectName("tableWidgetTotal")
        self.tableWidgetTotal.setColumnCount(9)
        self.tableWidgetTotal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTotal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTotal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTotal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTotal.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTotal.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTotal.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTotal.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTotal.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTotal.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab_4, "")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(550, 400, 81, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidgetJ1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetJ1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Candidate"))
        item = self.tableWidgetJ1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Popularity Tickets"))
        item = self.tableWidgetJ1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Event Tickets"))
        item = self.tableWidgetJ1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Theme Wear"))
        item = self.tableWidgetJ1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Swim Wear"))
        item = self.tableWidgetJ1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Confidence"))
        item = self.tableWidgetJ1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Audience Impact"))
        item = self.tableWidgetJ1.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Total"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Judge 1"))
        item = self.tableWidgetJ2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetJ2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Candidate"))
        item = self.tableWidgetJ2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Popularity Tickets"))
        item = self.tableWidgetJ2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Event Tickets"))
        item = self.tableWidgetJ2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Theme Wear"))
        item = self.tableWidgetJ2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Swim Wear"))
        item = self.tableWidgetJ2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Confidence"))
        item = self.tableWidgetJ2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Audience Impact"))
        item = self.tableWidgetJ2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Total"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Judge 2"))
        item = self.tableWidgetJ3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetJ3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Candidate"))
        item = self.tableWidgetJ3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Popularity Tickets"))
        item = self.tableWidgetJ3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Event Tickets"))
        item = self.tableWidgetJ3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Theme Wear"))
        item = self.tableWidgetJ3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Swim Wear"))
        item = self.tableWidgetJ3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Confidence"))
        item = self.tableWidgetJ3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Audience Impact"))
        item = self.tableWidgetJ3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Total"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Judge 3"))
        item = self.tableWidgetTotal.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetTotal.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Candidate"))
        item = self.tableWidgetTotal.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Popularity Tickets"))
        item = self.tableWidgetTotal.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Event Tickets"))
        item = self.tableWidgetTotal.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Theme Wear"))
        item = self.tableWidgetTotal.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Swim Wear"))
        item = self.tableWidgetTotal.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Confidence"))
        item = self.tableWidgetTotal.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Audience Impact"))
        item = self.tableWidgetTotal.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Total"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Total"))
        self.pushButton.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

