# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guidesign.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("#MainWindow\n"
"{\n"
"background-image: url(\'background.jpeg\')\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label9 = QtWidgets.QLabel(self.centralwidget)
        self.label9.setGeometry(QtCore.QRect(40, 230, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label9.setFont(font)
        self.label9.setStyleSheet("background-color: rgb(66, 134, 244);")
        self.label9.setAlignment(QtCore.Qt.AlignCenter)
        self.label9.setObjectName("label9")
        self.waterStatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.waterStatusLabel.setGeometry(QtCore.QRect(40, 160, 411, 71))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.waterStatusLabel.setFont(font)
        self.waterStatusLabel.setStyleSheet("")
        self.waterStatusLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.waterStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.waterStatusLabel.setWordWrap(True)
        self.waterStatusLabel.setObjectName("waterStatusLabel")
        self.shutdownButton = QtWidgets.QPushButton(self.centralwidget)
        self.shutdownButton.setGeometry(QtCore.QRect(370, 270, 81, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.shutdownButton.setFont(font)
        self.shutdownButton.setObjectName("shutdownButton")
        self.minimizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.minimizeButton.setGeometry(QtCore.QRect(280, 270, 81, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.minimizeButton.setFont(font)
        self.minimizeButton.setObjectName("minimizeButton")
        self.phLabel = QtWidgets.QLabel(self.centralwidget)
        self.phLabel.setGeometry(QtCore.QRect(100, 20, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.phLabel.setFont(font)
        self.phLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.phLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.phLabel.setObjectName("phLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(66, 134, 244);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.ORPLabel = QtWidgets.QLabel(self.centralwidget)
        self.ORPLabel.setGeometry(QtCore.QRect(260, 20, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ORPLabel.setFont(font)
        self.ORPLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.ORPLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ORPLabel.setObjectName("ORPLabel")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(66, 134, 244);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.datetimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.datetimeLabel.setGeometry(QtCore.QRect(40, 270, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.datetimeLabel.setFont(font)
        self.datetimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.datetimeLabel.setObjectName("datetimeLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Water Quality Effect</span></p></body></html>"))
        self.waterStatusLabel.setText(_translate("MainWindow", "<html><head/><body><p>-</p></body></html>"))
        self.shutdownButton.setText(_translate("MainWindow", "Shutdown"))
        self.minimizeButton.setText(_translate("MainWindow", "Minimize"))
        self.phLabel.setText(_translate("MainWindow", "0.00"))
        self.label_2.setText(_translate("MainWindow", "pH"))
        self.ORPLabel.setText(_translate("MainWindow", "0.00"))
        self.label_4.setText(_translate("MainWindow", "ORP"))
        self.datetimeLabel.setText(_translate("MainWindow", "0:00 00/00/0000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

